#! /bin/zsh
if [ -f /tmp/battwarn ]
then
	pkill $(cat /tmp/battwarn)
	rm /tmp/battwarn
fi
if [[ $(battery | grep Discharging | awk '$2<11') ]]
then
	$$ > /tmp/battwarn
fi
while [[ $(battery | grep Discharging | awk '$2<11') ]] ; do
	zenity --warning --text "Plug in charger."
	sleep 300
done
