PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=20
PANEL_TOP_GAP=6
PANEL_WM_NAME=bspwm_panel
PANEL_FONT="Liberation Sans:style=bold:size=9"
ICON_FONT="FontAwesome:size=11"
ICON_FONT2="FontAwesome:size=9"
ICON_FONT3="FontAwesome:size=7"
export PANEL_FIFO PANEL_HEIGHT PANEL_TOP_GAP PANEL_WM_NAME PANEL_FONT ICON_FONT ICON_FONT2 ICON_FONT3
