#! /bin/sh

source ~/.config/bspwm/panel_resources/colors

num_mon=$(bspc query -M | wc -l)
PADDING="  "
space="%{B$COLOR_SPACE}%{O6}%{B-}"
border="%{O$PANEL_LINE_WIDTH}"

session="$PADDING%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} $(whoami)@$(hostname) %{B-}%{F-}"

while read -r line ; do
	case $line in
		T*)
			# clock output
			time=" ${line#?} "
			;;
		B*)
			# battery status
			battery="${line#?}$PADDING"
			;;
		V*)
			# pulse volume
			volume="${line#?}"
			;;
		R*)
			# tray
			tray="${line#?}"
			;;
		U*)
			# update indicator
			update="${line#?}"
			;;
		W*)
			# bspwm's state
			wm=""
			tfgs=""
			tbgs=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}} ${name} %{B-}%{F-}"
						tfgs="${tfgs}%{F${FG}}:"
						tbgs="${tbgs}%{B${BG}}:"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}} ${name} %{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac

	if [[ $tfgs && $tbgs ]]; then
		i=0
		for tfg in $tfgs; do
			i=$((i+1))
			eval tfg${i}="$tfg"
		done
		i=0
		for tbg in $tbgs; do
			i=$((i+1))
			eval tbg${i}="$tbg"
		done
	else
		tfg1="%{F$COLOR_FOCUSED_MONITOR_FG}"
		tbg1="%{B$COLOR_FOCUSED_MONITOR_BG}"
	fi

	output="%{Sf}%{l}${space}${border}%{+u}%{+o}${wm}%{c}${tfg1}${tbg1}${time}%{B-}%{F-}%{r}${update}${tray}${battery}${volume}${session}%{-o}%{-u}${border}${space}"

	for j in $(seq 2 ${num_mon}); do
		tfgn=$(eval echo \$tfg${j})
		tbgn=$(eval echo \$tbg${j})
		output="${output}%{S+}%{l}${space}${border}%{+u}%{+o}${wm}%{c}${tfgn}${tbgn}${time}%{B-}%{F-}%{r}${update}${tray}${volume}${session}%{-o}%{-u}${border}${space}"
	done

	printf "%s\n" "$output"

done
