#! /bin/sh

#Check for battery

if [[ $(battery) ]] &> /dev/null ; then
	BATTEY_PRESENT=1
fi

while true ; do

	#Process states

	PS=$(ps -cax)

	##Telegram state

	TELEGRAM_PID=$(echo "$PS" | grep -m 1 "telegram-desk" | awk '{ print $1 }')

	if [[ $TELEGRAM_PID && ! $TELEGRAM_WID ]] ; then
		WIDS=$(xdo id -p $TELEGRAM_PID)
		TELEGRAM_WID=$(echo "$WIDS" | head -n $(xtitle $WIDS | grep -m 1 -n "Telegram" | cut -d: -f1) | tail -n 1)
	elif [[ ! $TELEGRAM_PID ]] ; then
		unset TELEGRAM_WID
	fi

	if [[ $TELEGRAM_WID ]] ; then
		TELEGRAM="%{T3}\uf1d8%{T-}$(xtitle $TELEGRAM_WID | tr -dc ' 0-9')  "
	else
		unset TELEGRAM
	fi

	##Dropbox state

	DROPBOX_RUN=$(echo "$PS" | grep -m 1 dropbox)

	if [[ $DROPBOX_RUN ]] ; then
		DROPBOX_STATE=$(dropbox-cli status)
	fi

	if [[ $DROPBOX_STATE = "Up to date" ]] ; then
		DROPBOX="\uf16b  "
	elif [[ $DROPBOX_RUN ]] ; then
		DROPBOX="\uf16b !  "
	else
		unset DROPBOX
	fi

	##Redshift state

	REDSHIFT_RUN=$(echo "$PS" | grep -m 1 redshift)

	if [[ $REDSHIFT_RUN ]] ; then
		REDSHIFT="\uf0eb  "
	else
		REDSHIFT="%{F#FF707880}\uf0eb%{F-}  "
	fi

	#Network interface state(s)

	##Set network icon variable(s)

	NIFS=$(ls -r /sys/class/net | grep '^e\|^w')

	for NIF in $NIFS ; do

		case ${NIF:0:1} in
			"e")
				eval ${NIF}_ICON="uf0e8"
				;;
			"w")
				eval ${NIF}_ICON="uf1eb"
				;;
		esac

	done

	##Print network interface state(s)

	unset NET
	IP=$(ip r)

	for NIF in $NIFS ; do
		NET_UP=$(echo "$IP" | grep $NIF)

		if [[ $NET_UP ]] ; then
			NET+=$(eval echo "'\'\$${NIF}_ICON")
			NET+="  "
		else
			NET+=$(eval echo "%{F#FF707880}'\'\$${NIF}_ICON%{F-}")
			NET+="  "
		fi

	done

	##VPN state

	VPN_STATE=$(cat /tmp/vpn_state)

	case $VPN_STATE in
		"Connected")
			VPN="\uf023  "
			;;
		"Disconnected")
			VPN="\uf09c  "
			;;
		*)
			VPN="%{F#FFCC6666}\uf023%{F-}  "
			;;
	esac

	#Battery state

	if [[ $BATTEY_PRESENT ]] ; then
		BATTERY=$(~/.config/bspwm/panel_resources/battery)
	fi

	#Pulseaudio volume

	VOLUME=$(~/.config/bspwm/panel_resources/volume)

	echo -e "R$TELEGRAM$DROPBOX$REDSHIFT$VPN$NET"
	echo -e "$BATTERY"
	echo -e "$VOLUME"

	sleep 1

done > "$PANEL_FIFO" &
