#! /bin/sh

#Check for battery

[[ $(battery) ]] &> /dev/null && BATTEY_PRESENT=1

while true ; do

	##Telegram state

	TELEGRAM_PID=$(pgrep -f telegram-desktop)

	if [[ $TELEGRAM_PID && ! $TELEGRAM_WID ]] ; then
		WIDS=$(xdo id -p $TELEGRAM_PID)
		TELEGRAM_WID=$(echo "$WIDS" | head -n $(xtitle $WIDS | grep -m 1 -n "Telegram" | cut -d: -f1) | tail -n 1)
	elif [[ ! $TELEGRAM_PID ]] ; then
		unset TELEGRAM_WID
	fi

	if [[ $TELEGRAM_WID && $(xtitle $TELEGRAM_WID | tr -dc '0-9') ]] ; then
		TELEGRAM=" %{T3}\uf1d8%{T-} "
	elif [[ $TELEGRAM_WID ]] ; then
		TELEGRAM=" %{T3}\uf1d9%{T-} "
	else
		TELEGRAM=" %{F#FF707880}%{T3}\uf1d9%{T-}%{F-} "
	fi

	##Dropbox state

	DROPBOX_RUN=$(pgrep dropbox)

	[[ $DROPBOX_RUN ]] && DROPBOX_STATE=$(dropbox-cli status)

	if [[ $DROPBOX_STATE = "Up to date" ]] ; then
		DROPBOX=" \uf16b "
	elif [[ $(echo "$DROPBOX_STATE" | grep "Syncing") ]] ; then
		DROPBOX=" %{F#FF5F875F}\uf16b%{F-} "
	elif [[ $DROPBOX_RUN ]] ; then
		DROPBOX=" %{F#FFA54242}\uf16b%{F-} "
	else
		DROPBOX=" %{F#FF707880}\uf16b%{F-} "
	fi

	##Redshift state

	REDSHIFT_RUN=$(pgrep redshift)

	if [[ $REDSHIFT_RUN ]] ; then
		REDSHIFT=" \uf0eb "
	else
		REDSHIFT=" %{F#FF707880}\uf0eb%{F-} "
	fi

	#Network interface state(s)

	##VPN state

	VPN_STATE=$(cat /tmp/vpn_state)

	case $VPN_STATE in
		"Connected")
			VPN=" \uf023 "
			;;
		"Disconnected")
			VPN=" %{F#FF707880}\uf023%{F-} "
			;;
		*)
			VPN=" %{F#FFA54242}\uf023%{F-} "
			;;
	esac

	##Set network icon variable(s)

	NIFS=$(ls -r /sys/class/net | grep '^e\|^w')

	for NIF in $NIFS ; do

		case ${NIF:0:1} in
			"e")
				eval ${NIF}_ICON="uf0e8"
				;;
			"w")
				eval ${NIF}_ICON="uf1eb"
				;;
		esac

	done

	##Print network interface state(s)

	unset NET
	IP=$(ip r)
	NET+=" "

	for NIF in $NIFS ; do
		NET_UP=$(echo "$IP" | grep $NIF)

		if [[ $NET_UP ]] ; then
			NET+=$(eval echo "'\'\$${NIF}_ICON")
			NET+="  "
		else
			NET+=$(eval echo "%{F#FF707880}'\'\$${NIF}_ICON%{F-}")
			NET+="  "
		fi

	done

	#Battery state

	[[ $BATTEY_PRESENT ]] && BATTERY=$(~/.config/bspwm/panel_resources/battery)

	#Pulseaudio volume

	VOLUME=$(~/.config/bspwm/panel_resources/volume)

	echo -e "R $TELEGRAM$DROPBOX$REDSHIFT$VPN$NET"
	echo -e "$BATTERY"
	echo -e "$VOLUME"

	sleep 1

done > "$PANEL_FIFO" &
