#! /bin/bash

source ~/.config/bspwm/panel_resources/colors
OFFICIAL_U=$(checkupdates | wc -l)
AUR_U=$(trizen -Quaq | wc -l)
((UPDATES = $OFFICIAL_U + $AUR_U))

if [[ $UPDATES -gt 0 ]] ; then
	UPDATES="\uf0aa"
else
	UPDATES="%{F#FF707880}\uf0aa%{F-}"
fi

echo -e "U$UPDATES"
