#! /bin/sh

OFFICIAL_U=$(checkupdates | wc -l)
AUR_U=$(checkupdates-aur | wc -l)
((UPDATES = $OFFICIAL_U + $AUR_U))

if [[ $UPDATES > 0 ]] ; then
	UPDATES="\uf0aa $UPDATES"
else
	unset UPDATES
fi

echo -e "U$UPDATES"
