#! /bin/sh

OFFICIAL_U=$(checkupdates | wc -l)
AUR_U=$(cower -q -u --threads=5 | wc -l) 2> /dev/null
((UPDATES = $OFFICIAL_U + $AUR_U))

if [[ $UPDATES > 0 ]] ; then
	UPDATES="\uf0aa $UPDATES  "
else
	unset UPDATES
fi

echo -e "U$UPDATES"
