#! /bin/zsh

pacmd info | grep -e "Default sink.*alsa_output.usb-Corsair_CORSAIR_VOID_ELITE_Wireless_Gaming_Dongle-00.analog-stereo" && ICON="uf025" || ICON="uf028"

volume -d 'pulse' | read -r MUTE VOL

if [[ $MUTE == "off" ]] ; then
	VOL="%{F#FF707880}\\${ICON} $VOL%"
else
	VOL="\\${ICON} $VOL%"
fi

echo "V$VOL"
