#! /bin/zsh

pacmd info | grep -e "Default sink.*alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game" && ICON="uf025" || ICON="uf028"

volume -d 'pulse' | read -r MUTE VOL

if [[ $MUTE == "off" ]] ; then
	VOL="%{F#FF707880}\\${ICON} $VOL%"
else
	VOL="\\${ICON} $VOL%"
fi

echo "V$VOL"
