#! /bin/sh

#Basic config
bspc config border_width					1
bspc config split_ratio						0.5
bspc config window_gap						6
bspc config click_to_focus					button1
bspc config focus_follows_pointer			false
bspc config pointer_follows_focus			false
bspc config pointer_follows_monitor			true
bspc config swallow_first_click				false
bspc config initial_polarity 				first_child
bspc config ignore_ewmh_focus				true
bspc config remove_disabled_monitors		false
bspc config remove_unplugged_monitors		false
bspc config external_rules_command			~/.config/bspwm/external_rules.sh

#Colors
bspc config focused_border_color			'#C0B0C5'
bspc config normal_border_color				'#282A2E'
bspc config presel_feedback_color			'#A54242'
bspc config active_border_color				'#808080'


#Monitor settings and rules
bspc monitor primary -n Primary
bspc monitor Primary -d 1 2 3 4 5 6 7 8

case $(bspc query -M | wc -l) in
	2)
		bspc monitor east -n East
		bspc monitor East -d 1 2 3 4 5 6 7 8
		bspc rule -a Spotify 							desktop='^2'
		bspc rule -a TelegramDesktop 					desktop='^1'
		bspc rule -a Skype 								dekstop='^1' state=pseudo_tiled
		bspc rule -a discord 							desktop='^1' state=pseudo_tiled
		bspc rule -a "Microsoft Teams - Insiders" 		desktop='^3'
		;;
	*)
		bspc rule -a Spotify 							desktop='^7'
		bspc rule -a SVPManager 						desktop='^6' state=pseudo_tiled
		bspc rule -a qBittorrent 						desktop='^6'
		bspc rule -a TelegramDesktop 					desktop='^8'
		bspc rule -a Skype 								dekstop='^8' state=pseudo_tiled
		;;
esac

bspc rule -a SpeedCrunch 								state=pseudo_tiled
bspc rule -a URxvt:scratchpad 							sticky=on state=floating locked=on hidden=on
bspc rule -a Zathura 									state=tiled
bspc rule -a Google-chrome 								desktop='^3'

feh --bg-fill ~/wallpaper.png &
nvidia-settings -l &

#Panel
pgrep -f "bspwm/panel" || ~/.config/bspwm/panel &
