#! /bin/sh

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $(( $PANEL_HEIGHT + $PANEL_TOP_GAP ))
source ~/.config/bspwm/panel_resources/colors
bspc subscribe report > "$PANEL_FIFO" &

clock -sf 'S%A %d %B %H:%M' > "$PANEL_FIFO" &
source ~/.config/bspwm/panel_resources/tray

while true ; do
	~/.config/bspwm/panel_resources/updates 2> /dev/null > "$PANEL_FIFO"
	sleep 1h
done &

~/.config/bspwm/panel_resources/bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT++$PANEL_TOP_GAP -o 0 -f "$PANEL_FONT" -o 0 -f "$ICON_FONT" -o -2 -f "$ICON_FONT2" -o -3 -f "$ICON_FONT3" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" -U "$COLOR_DEFAULT_BG" -u "$PANEL_LINE_WIDTH" | sh &

wids=$(xdo id -m -a "$PANEL_WM_NAME")
for wid in $wids; do
	xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
done

wait
