#! /bin/zsh

battery -s | while read -r CHAR BATT ; do

case $BATT in
	[8-9]?|100)
		LEVEL="\uf240"
		;;
	[6-7]?)
		LEVEL="\uf241"
		;;
	[4-5]?)
		LEVEL="\uf242"
		;;
	[2-3]?)
		LEVEL="\uf243"
		;;
	1?)
		LEVEL="\uf244"
		;;
	[0-9])
		LEVEL="%{F#FFA54242}\uf244%{F-}"
		;;
	*)
		LEVEL="%{F#FFA54242}\uf071%{F-}"
		;;
esac

if [[ $CHAR == "Charging" || $BATT=100 && $(acpi | grep "zero rate") ]] ; then
	BOLT="%{T3} \uf0e7%{T-}"
else
	unset BOLT
fi

echo "B$LEVEL$BOLT"

if [[ $BATT -le 9  && ! -f /tmp/BATTwarn ]] ; then
	~/dotfiles/BATTwarn &
fi

done
