#! /bin/zsh
battery -s | while read -r line ; do
	echo $line | { read char batt }
	if [[ $char == "Charging" || $batt=100 && $(acpi | grep "zero rate") ]]
	then
		bolt="%{T3} \uf0e7%{T-}"
	else
		unset bolt
	fi
	if [[ $batt -ge 86 ]]
	then
		level="\uf240"
	elif [[ $batt -ge 66 ]]
	then
		level="\uf241"
	elif [[ $batt -ge 46 ]]
	then
		level="\uf242"
	elif [[ $batt -ge 26 ]]
	then
		level="\uf243"
	elif [[ $batt -ge 11 ]]
	then
		level="\uf244"
	elif [[ $batt -le 10  && ! -f /tmp/battwarn ]]
	then
		~/dotfiles/battwarn &
		level="%{F#FFA54242}\uf244%{F-}"
	elif [[ $batt -le 10 && -f /tmp/battwarn ]]
	then
		level="%{F#FFA54242}\uf244%{F-}"
	else
		level="%{F#FFA54242}\uf071%{F-}"
	fi
	echo "B$level$bolt"
done > "$PANEL_FIFO" &
