#! /bin/sh

xsetroot -cursor_name left_ptr &
pgrep -x compton > /dev/null || compton -t -8 -l -9 -r 6 -o 0.7 &
unclutter --timeout 1 &
dropbox &

bspc config border_width       1
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config pointer_follows_monitor	true 
bspc config click_to_focus 		button1 
bspc config swallow_first_click	false
bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focused_border_color '#C5C8C6'
bspc config normal_border_color '#282A2E'
bspc config presel_feedback_color '#A54242'
#bspc config active_border_color '#C5C8C6'

if [[ $(hostname) == 'amunet' ]]
then
	bspc config window_gap 6
	bspc monitor primary -d 1 2 3 4 5 6
	bspc monitor east -d 1 2 3 4 5 6
	feh --bg-fill ~/wallpaper1.jpg --bg-fill ~/wallpaper2.jpg &

	bspc rule -a TelegramDesktop state=pseudo_tiled locked=on desktop='east:^6'
	bspc rule -a SVPManager state=pseudo_tiled desktop='primary:^6'
	bspc rule -a Spotify desktop='east:^2'
else
	bspc config window_gap 4
	bspc monitor primary -d 1 2 3 4 5 6 7 8
	feh --bg-fill ~/wallpaper.jpg &

	bspc rule -a TelegramDesktop state=pseudo_tiled locked=on desktop='^8'
	bspc rule -a Spotify desktop='^2'
fi

bspc rule -a URxvt:scratchpad sticky=on state=floating locked=on hidden=on
bspc rule -a SpeedCrunch state=floating
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating

pgrep -x panel || ~/.config/bspwm/panel &
~/dotfiles/scratchpad &
