#! /bin/sh

xsetroot -cursor_name left_ptr &
feh --bg-fill ~/wallpaper.jpg &
pgrep -x compton > /dev/null || compton --respect-prop-shadow -bc -t -8 -l -9 -r 6 -o 0.7 &
dropbox &

bspc config border_width       1
bspc config window_gap         6

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true 
bspc config pointer_follows_monitor on
bspc config click_to_focus 		true 
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focused_border_color '#C5C8C6'
bspc config normal_border_color '#282A2E'
bspc config presel_feedback_color '#A54242'
#bspc config active_border_color '#C5C8C6'

bspc monitor -d 1 2 3 4 5 6

bspc desktop 1 -l monocle

bspc rule -a URxvt:scratchpad border=off sticky=on state=floating locked=on
bspc rule -a Firefox desktop 1
#bspc rule -a vivaldi-preview desktop 1
bspc rule -a Vlc state=floating
bspc rule -a Speedcrunch state=floating
bspc rule -a Spotify desktop 2
bspc rule -a telegram-desktop border=off state=floating locked=on desktop='^6'
#bspc rule -a sun-awt-X11-XFramePeer state=floating

~/.config/bspwm/panel | sh &

