#! /bin/zsh

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $(( $PANEL_HEIGHT + 6 ))
bspc subscribe report | sed -u 's/HDMI-A-0/Primary/; s/DVI-D-0/East/' > "$PANEL_FIFO" &
xtitle -sf 'T%s\n' -t 110 > "$PANEL_FIFO" &
clock -sf 'S%A %d %B %H:%M' > "$PANEL_FIFO" &

source ~/.config/bspwm/volume
source ~/.config/bspwm/tray

while true;
do
	~/.config/bspwm/updates
	sleep 1h
done > "$PANEL_FIFO" &

source ~/.config/bspwm/panel_colors

~/.config/bspwm/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT++6 -f "$PANEL_FONT" -f "$ICON_FONT" -f "$ICON_FONT2" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &> /dev/null

wid=$(xdo id -m -a "$PANEL_WM_NAME")
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
