#! /bin/zsh

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config -m primary top_padding $(( $PANEL_HEIGHT + 2 ))
bspc subscribe report | sed -u 's/HDMI-0/Primary/; s/DVI-0/East/' > "$PANEL_FIFO" &
xtitle -sf 'T%s\n' -t 110 > "$PANEL_FIFO" &
clock -sf 'S%A %d %B %H:%M' > "$PANEL_FIFO" &

source ~/.config/bspwm/volume
source ~/.config/bspwm/tray

while true;
do
	~/.config/bspwm/updates
	sleep 1h
done > "$PANEL_FIFO" &

source ~/.config/bspwm/panel_colors

~/.config/bspwm/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g 2548x$PANEL_HEIGHT+6+2 -f "$PANEL_FONT" -f "$ICON_FONT" -f "$ICON_FONT2" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
