#! /bin/zsh

POLL_DELAY=0

while true;
do
	#Process states

	PS=$(ps -cax)

	##Telegram state

	TELEGRAM_PID=$(echo $PS | grep telegram-desk | cut -d " " -f3)

	if [[ $TELEGRAM_PID && !$TELEGRAM_WID ]]
	then
		eval "WIDS=($(xdotool search --pid ${TELEGRAM_PID}))"
		TELEGRAM_WID=$(for WID in ${WIDS}; do; xwininfo -id $WID | grep '"Telegram' | cut -d " " -f4; done)
	elif [[ !$TELEGRAM_PID && $TELEGRAM_WID ]]
	then
		TELEGRAM_WID=""
	fi

	if [[ $TELEGRAM_WID ]]
	then
		TELEGRAM_MES=$(xprop -id $TELEGRAM_WID WM_NAME | tr -dc '0-9')
	fi

	if [[ $TELEGRAM_MES ]]
	then
		TELEGRAM="%{T3}\uf1d8%{T-} $TELEGRAM_MES  "
		TELEGRAM_MES=""
	elif [[ $TELEGRAM_WID && !$TELEGRAM_MES ]]
	then
		TELEGRAM="%{T3}\uf1d8%{T-}  "
	elif [[ $TELEGRAM_PID ]]
	then
		TELEGRAM="%{T3}%{F#FFCC6666}\uf1d8%{T-}%{F-}%{T-}  "
	else
		TELEGRAM=""
	fi

	##Dropbox state

	DROPBOX_RUN=$(echo $PS | grep dropbox)
	if [[ $DROPBOX_RUN ]]
	then
		DROPBOX_STATE=$(dropbox-cli status)
	fi
	if [[ $DROPBOX_STATE == "Up to date" ]]
	then
		DROPBOX="\uf16b  "
	elif [[ $DROPBOX_RUN && $DROPBOX_STATE != "Up to date" ]]
	then
		DROPBOX="\uf16b !  "
	else
		DROPBOX=""
	fi

	##Redshift state

	REDSHIFT_RUN=$(echo $PS | grep redshift)
	if [[ $REDSHIFT_RUN ]]
	then
		REDSHIFT="\uf0eb  "
	else
		REDSHIFT="%{F#FF707880}\uf0eb%{F-}  "
	fi

	#Network interface state(s)

	##Set network variables

	NIFS=$(ls -r /sys/class/net | grep '^e\|^w')

	for NIF in $NIFS
	do
		if [[ ${NIF:0:1} == "e" ]]
		then
			eval "$NIF"_ICON="uf0e8"
		elif [[ ${NIF:0:1} == "w" ]]
		then
			eval "$NIF"_ICON="uf1eb"
		fi
	done

	IP=$(ip r)

	##Print network interface state(s)

	NET=""

	for NIF in $NIFS
	do
		NET_UP=$(echo $IP | grep $NIF)
		if [[ $NET_UP ]]
		then
			NET+="\\${(P)$(echo "$NIF"_ICON)}  "
		else
			NET+="%{F#FF707880}\\${(P)$(echo "$NIF"_ICON)}%{F-}  "
		fi
	done

	##VPN state

	VPN_UP=$(echo $IP | grep azirevpn)
	if [[ $VPN_UP && $POLL_DELAY == 0 ]]
	then
		VPN_CONNECTED=$(curl https://api.azirevpn.com/v1/check | grep '"connected": true')
		POLL_DELAY=$(((POLL_DELAY + 1) % 10))
	fi
	if [[ $VPN_UP && $VPN_CONNECTED ]]
	then
		VPN="\uf023  "
	elif [[ $VPN_UP && !$VPN_CONNECTED ]]
	then
		VPN="%{F#FFCC6666}\uf023%{F-}  "
	else
		VPN="\uf09c  "
	fi

	#Pulseaudio volume

	VOLUME=$(~/.config/bspwm/volume_poll)

	echo "R$TELEGRAM$DROPBOX$REDSHIFT$VPN$NET"
	echo "$VOLUME"

	sleep 1
done > "$PANEL_FIFO" &
