#! /bin/zsh

while true;
do
	PS=$(ps -cax)
	
	TELEGRAM_RUN=$(echo $PS | grep telegram)
	if [[ $TELEGRAM_RUN ]]
	then
		TELEGRAM_MES=$(xdotool search --class "TelegramDesktop" getwindowname | awk '{print $2}' | sed 's/^.\(.*\).$/\1/')
	fi
	if [[ $TELEGRAM_MES ]]
	then
		TELEGRAM="\uf1d8 $TELEGRAM_MES  "
		TELEGRAM_MES=""
	elif [[ $TELEGRAM_RUN && !$TELEGRAM_MES ]]
	then
		TELEGRAM="\uf1d8  "
	else
		TELEGRAM=""
	fi

	DROPBOX_RUN=$(echo $PS | grep dropbox)
	if [[ $DROPBOX_RUN ]]
	then
		DROPBOX_STATE=$(dropbox-cli status | sed 's/Up to date/1/')
	fi
	if [[ $DROPBOX_STATE == 1 ]]
	then
		DROPBOX="\uf16b  "
	elif [[ $DROPBOX_RUN && $DROPBOX_STATE != 1 ]]
	then
		DROPBOX="\uf16b !  "
	else
		DROPBOX=""
	fi

	REDSHIFT_RUN=$(echo $PS | grep redshift)
	if [[ $REDSHIFT_RUN ]]
	then
		REDSHIFT="\uf0eb  "
	else
		REDSHIFT="%{F#FF707880}\uf0eb%{F-}  "
	fi

	VPN_UP=$(ip link | grep tun0)
	if [[ $VPN_UP ]]
	then
		VPN="\uf023  "
	else
		VPN="\uf09c  "
	fi
	
	echo "R$TELEGRAM$DROPBOX$REDSHIFT$VPN"

	sleep 1
done > "$PANEL_FIFO" &
