#! /bin/zsh

#Set network variables

NIFS=($(ls -r /sys/class/net | grep '^e\|^w'))

for NIF in $NIFS
do
	if [[ ${NIF:0:1} == "e" ]]
	then
		eval "$NIF"_ICON="uf0e8"
	elif [[ ${NIF:0:1} == "w" ]]
	then
		eval "$NIF"_ICON="uf1eb"
	fi
done

while true;
do
	PS=$(ps -cax)

	#Telegram state

	TELEGRAM_RUN=$(echo $PS | grep telegram)
	if [[ $TELEGRAM_RUN ]]
	then
		TELEGRAM_MES=$(xdotool search --class "TelegramDesktop" getwindowname | tr -dc '0-9')
	fi
	if [[ $TELEGRAM_MES ]]
	then
		TELEGRAM="%{T3}\uf1d8%{T-} $TELEGRAM_MES  "
		TELEGRAM_MES=""
	elif [[ $TELEGRAM_RUN && !$TELEGRAM_MES ]]
	then
		TELEGRAM="%{T3}\uf1d8%{T-}  "
	else
		TELEGRAM=""
	fi

	#Dropbox state

	DROPBOX_RUN=$(echo $PS | grep dropbox)
	if [[ $DROPBOX_RUN ]]
	then
		DROPBOX_STATE=$(dropbox-cli status)
	fi
	if [[ $DROPBOX_STATE == "Up to date" ]]
	then
		DROPBOX="\uf16b  "
	elif [[ $DROPBOX_RUN && $DROPBOX_STATE != "Up to date" ]]
	then
		DROPBOX="\uf16b !  "
	else
		DROPBOX=""
	fi

	#Redshift state

	REDSHIFT_RUN=$(echo $PS | grep redshift)
	if [[ $REDSHIFT_RUN ]]
	then
		REDSHIFT="\uf0eb  "
	else
		REDSHIFT="%{F#FF707880}\uf0eb%{F-}  "
	fi

	#VPN state

	IP=$(ip r)

	VPN_UP=$(echo $IP | grep tun0)
	if [[ $VPN_UP ]]
	then
		VPN="\uf023  "
	else
		VPN="\uf09c  "
	fi

	#Network interface state(s)

	NET=""

	for NIF in $NIFS
	do
		NET_UP=$(echo $IP | grep $NIF)
		if [[ $NET_UP ]]
		then
			NET+="\\${(P)$(echo "$NIF"_ICON)}  "
		else
			NET+="%{F#FF707880}\\${(P)$(echo "$NIF"_ICON)}%{F-}  "
		fi
	done

	echo "R$TELEGRAM$DROPBOX$REDSHIFT$VPN$NET"

	sleep 1
done > "$PANEL_FIFO" &
