#! /bin/zsh

while true;
do
	OFFICIAL_U=$(checkupdates | wc -l)
	AUR_U=$(cower -u | wc -l)
	((UPDATES = $OFFICIAL_U + $AUR_U))

	if [[ $UPDATES > 0 ]]
	then
		echo "U\uf06a $UPDATES  "
	else
		echo "U"
	fi

	sleep 1h
done > "$PANEL_FIFO" &
