#! /bin/zsh

volume -d 'pulse' -f '%s %i' | read -r mute vol

	if [[ $mute == "off" ]]
	then
		echo "V\uf026%{T4}\uf00d%{T-}"
	elif [[ $vol -ge 50 ]]
	then
		echo "V\uf028 $vol%"
	elif [[ $vol -lt 50 && $vol -gt 0 ]]
	then
		echo "V\uf027 $vol%"
	elif [[ $vol -eq 0 ]]
	then
		echo "V\uf026 $vol%"
	fi 
