#! /bin/zsh

volume -d 'pulse' -si 4 -f '%s %i' | while read -r line ; do
	echo $line | { read mute vol }
	if [[ $mute == "off" ]]
	then
		echo "V\uf3b9"
	elif [[ $vol -ge 50 ]]
	then
		echo "V\uf3ba $vol%"
	elif [[ $vol -lt 50 && $vol -gt 0 ]]
	then
		echo "V\uf3b7 $vol%"
	elif [[ $vol -eq 0 ]]
	then
		echo "V\uf3b8 $vol%"
	fi
done > "$PANEL_FIFO" &
