#! /bin/sh

bspc config border_width       1
bspc config window_gap         6

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config pointer_follows_monitor on
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config focused_border_color '#C5C8C6'
bspc config normal_border_color '#282A2E'
bspc config presel_border_color '#A54242'
bspc config urgent_border_color '#A54242'
#bspc config active_border_color '#C5C8C6'

bspc monitor -d 1 2 3 4 5 6

bspc desktop 1 -l monocle

bspc rule -a scratchpad border=off sticky=on floating=on locked=on
#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox border=off desktop 1
bspc rule -a vlc floating=on
bspc rule -a speedcrunch floating=on
bspc rule -a Spotify desktop 2
bspc rule -a Steam border=off
bspc rule -a Telegram border=off floating=on locked=on desktop 6
bspc rule -a telegram border=off floating=on locked=on desktop 6
#bspc rule -a sun-awt-X11-XFramePeer floating=on

xsetroot -cursor_name left_ptr &
feh --bg-fill ~/wallpaper.jpg &
~/.config/bspwm/panel | sh &
