#! /bin/zsh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' -t 110 > "$PANEL_FIFO" &
clock -sf 'S%A %d %B %H:%M' > "$PANEL_FIFO" &

source ~/.config/bspwm/volume
source ~/.config/bspwm/battery
source ~/.config/bspwm/tray
source ~/.config/bspwm/kbstat.sh

source ~/.config/bspwm/panel_colors

cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$ICON_FONT" -f "$ICON_FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
