#! /bin/zsh
volume -d 'pulse' -si 1 -f '%s %i' | while read -r line ; do
	echo $line | { read mute vol }
	if [[ $mute == "off" ]]
	then
		echo "V\uf026 Muted"
	elif [[ $vol -ge 50 ]]
	then
		echo "V\uf028 $vol%"
	elif [[ $vol -lt 50 && $vol -gt 0 ]]
	then
		echo "V\uf027 $vol%"
	elif [[ $vol -eq 0 ]]
	then
		echo "V\uf026 $vol%"
	fi
done > "$PANEL_FIFO" &