#! /bin/zsh

volume -d 'pulse' -f '%s %i' | read -r MUTE VOL

if [[ $MUTE == "off" ]] ; then
	VOL="\uf026%{T4}\uf00d%{T-}"
else
	case $VOL in
		[0-9])
			VOL="\uf026 $VOL%"
			;;
		[1-4]?)
			VOL="\uf027 $VOL%"
			;;
		*)
			VOL="\uf028 $VOL%"
			;;
	esac
fi

echo "V$VOL"
