#!/bin/sh

userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources

num_mon=$(xrandr | grep connected | grep -v disconnected | wc -l)

case $(hostname) in
	"freja")
		#xrandr --output DP-0 --auto --primary
		xrandr --output DP-0 --mode 2560x1440 --rate 144.00 --primary
		xrandr --output DP-2 --auto --left-of DP-0
		;;
	"TUE009888")
		## HYBRID
		#xrandr --output eDP-1 --auto --primary
 		#xrandr --output DP-0 -right-of eDP-1-1

		## INTEL
		#xrandr --output eDP-1 --auto --primary
		#xrandr --output HDMI-1 --auto --right-of eDP-1

		## NVIDIA
		xrandr --output DP-3 --auto --primary
		xrandr --output DP-0 --auto --right-of DP-3
		#xrandr --output DP-0 --mode 1920x1080 --right-of DP-3
		xrandr --dpi 96
esac

#Merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

#Startup
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

export QT_QPA_PLATFORMTHEME='qt5ct'
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1.0

export MONITOR1=primary
case $(hostname) in
	"freja")
		case $num_mon in
			2)
				export MONITOR1=primary
				export MONITOR2=West
				;;
		esac
		;;
	"TUE009888")
		export MOZ_USE_XINPUT2=1
		case $num_mon in
			2)
				export MONITOR1=East
				export MONITOR2=primary
				;;
		esac
		;;
esac

export SSH_PORT=$(cat ~/.ssh_port)

eval $(keychain --eval --quiet --noask --nogui --confhost)
eval $(dircolors -b ~/.dir_colors)

xset s off -dpms &
xsetroot -cursor_name left_ptr &
##Utilities
numlockx &
urxvtd -q -f -o &
unclutter --timeout 1 &
xbindkeys &
redshift &
##Scripts
~/dotfiles/sysscripts/vpncheck.sh &
~/dotfiles/sysscripts/scratchpad.sh &
##Compositor
pgrep -x picom > /dev/null || picom &

conky &
sxhkd &

case $(hostname) in
	"TUE009888")
#		~/dotfiles/sysscripts/touchpadtoggle.sh &
		exec bspwm
		;;
	*)
		exec bspwm
		;;
esac
