#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

case $(hostname) in
	"freja")
		xrandr --output DP-0 --auto --primary
		;;
	"fjorgyn")
		#xrandr --output eDP-1-1 --gamma 1.15:1.15:1.15 --primary
		#xrandr --output DP-0 --gamma 0.85:0.85:0.85 --right-of eDP-1-1
		xrandr --output DP-3 --gamma 1.15:1.15:1.15 --primary
		xrandr --output DP-0 --gamma 0.90:0.90:0.90 --right-of DP-3
		#xrandr --output DP-0 --auto --right-of DP-3
		xrandr --dpi 96
esac

#Merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then

    xmodmap $sysmodmap

fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then

    xmodmap "$usermodmap"

fi

#Startup

if [ -d /etc/X11/xinit/xinitrc.d ] ; then

 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f

fi

export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'

export QT_QPA_PLATFORMTHEME='qt5ct'
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1.0

case $(hostname) in
	"nerthus")
		export MOZ_USE_XINPUT2=1
		;;
esac

export SSH_PORT=$(cat ~/.ssh_port)

eval $(keychain --eval --quiet --noask --nogui --confhost)
eval $(dircolors -b ~/.dir_colors)

xset s off -dpms &
xsetroot -cursor_name left_ptr &
##Utilities
numlockx &
#udiskie &
urxvtd -q -f -o &
unclutter --timeout 1 &
#dropbox &
xbindkeys &
redshift &
##Scripts
~/dotfiles/sysscripts/vpncheck.sh &
~/dotfiles/sysscripts/scratchpad.sh &
##Compositor
pgrep -x compton > /dev/null || allow_rgb10_configs=false compton -t -8 -l -9 -r 6 -o 0.7 &

sxhkd &

case $(hostname) in
	"fjorgyn")
		~/dotfiles/sysscripts/touchpadtoggle.sh &
		exec bspwm
		;;
	*)
		exec bspwm
		;;
esac
